apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: jobsets.batch.jobset.sigs.k8s.io
  annotations:
    api-approved.kubernetes.io: "unapproved-for-testing"
spec:
  group: batch.jobset.sigs.k8s.io
  names:
    kind: JobSet
    listKind: JobSetList
    plural: jobsets
    singular: jobset
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parallelism:
                  type: integer
                completions:
                  type: integer
                template:
                  type: object
